project_id = "geglemxrugxnmfwymtec"

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.google-calendar-auto-sync]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false

[functions.send-email-reminders]
verify_jwt = false
